batch_size: 4
dataset: sst2
eval_steps: 5
fp16: false
ge_config: default
learning_rate: 3.0e-05
local_rank: 0
loss_rate: 0.001
loss_type: ber
max_length: 64
max_samples: 100
max_steps: 20
model_name: gpt2
output_dir: test_output
patience: 3
seed: 1234
target_accuracy: 0.9
tensor_parallel_size: 2
weight_decay: 0.01
