batch_size: 8
dataset: winogrande
eval_steps: 100
fp16: false
learning_rate: 2.0e-05
local_rank: 0
loss_rate: 0.001
max_length: 256
max_samples: 0
max_steps: 100000
model_name: gpt2-large
output_dir: output_gpt2-medium/tp_Llama3.2-1B_precision-fp32_Num_Nodes-4_Data-winogrande_lr0.001_batch_size_8_test_2
patience: 3
seed: 1234
target_accuracy: 0.95
tensor_parallel_size: 4
weight_decay: 0.01
