batch_size: 16
dataset: winogrande
eval_steps: 100
fp16: true
learning_rate: 3.0e-05
local_rank: 0
loss_rate: 0.001
max_length: 128
max_samples: 0
max_steps: 100000
model_name: gpt2-large
output_dir: output_gpt2-large_winogrande/tp_gpt2-large_precision-fp16_Num_Nodes-2_lr0.001
patience: 3
seed: 1234
target_accuracy: 0.95
tensor_parallel_size: 2
weight_decay: 0.01
