batch_size: 16
dataset: mnli
eval_steps: 20
fp16: false
ge_config: ber_20
learning_rate: 3.0e-05
local_rank: 0
loss_rate: 0.001
loss_type: g-e
max_length: 128
max_samples: 0
max_steps: 100000
model_name: gpt2-large
output_dir: output_gpt2-large_BurstyLosses_mnli/tp_gpt2-large_precision-fp32_Num_Nodes-4_ge_config_ber_20_Short_Burst_Loss_Iteration_1
patience: 10
seed: 1234
target_accuracy: 0.75
tensor_parallel_size: 4
weight_decay: 0.01
